services:
  web:
    build: ./app
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    command: go run ./cmd/main.go -b 0.0.0.0
    depends_on:
      - db
      - cache
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      - RDB_PASSWORD=${RDB_PASSWORD}
    privileged: true
    ports:
      - '6397:6397'
    depends_on:
      - db
    command: >
      /bin/sh -c "
        sysctl vm.overcommit_memory=1 &&
        redis-server --save 20 1 --loglevel warning --requirepass $${RDB_PASSWORD}
      "
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  postgres-db: